a = 4

assert(a<5)
print("断言成功，程序继续")

assert(a>4)  # 断言失败，程序报错,测试调试使用